version: '3.8'

services:
  ffc-grants-frontend:
    command: npm run start:watch
    build:
      target: development
    image: ffc-grants-frontend-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  pa11y:
    image: defradigital/ffc-pa11y
    depends_on:
      - ffc-grants-frontend
    command: sh -c "scripts/wait ffc-grants-frontend:3000 -- pa11y-ci -c pa11y.json"
    volumes:
      - ./pa11y.json:/home/node/pa11y.json
      - ./test-output/:/home/node/test-output/
      - ./scripts/:/home/node/scripts
